# Form implementation generated from reading ui file 'src/GUI_UIs/ui_ai_token_usage.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_AiTokenUsage(object):
    def setupUi(self, Dialog_AiTokenUsage):
        Dialog_AiTokenUsage.setObjectName("Dialog_AiTokenUsage")
        Dialog_AiTokenUsage.resize(720, 560)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_AiTokenUsage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(parent=Dialog_AiTokenUsage)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 4)
        self.label_summary = QtWidgets.QLabel(parent=Dialog_AiTokenUsage)
        self.label_summary.setText("")
        self.label_summary.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_summary.setWordWrap(True)
        self.label_summary.setObjectName("label_summary")
        self.gridLayout.addWidget(self.label_summary, 1, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog_AiTokenUsage)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_models = QtWidgets.QWidget()
        self.tab_models.setObjectName("tab_models")
        self.gridLayout_models = QtWidgets.QGridLayout(self.tab_models)
        self.gridLayout_models.setObjectName("gridLayout_models")
        self.tableWidget_models = QtWidgets.QTableWidget(parent=self.tab_models)
        self.tableWidget_models.setAlternatingRowColors(True)
        self.tableWidget_models.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget_models.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_models.setObjectName("tableWidget_models")
        self.tableWidget_models.setColumnCount(0)
        self.tableWidget_models.setRowCount(0)
        self.gridLayout_models.addWidget(self.tableWidget_models, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_models, "")
        self.tab_tasks = QtWidgets.QWidget()
        self.tab_tasks.setObjectName("tab_tasks")
        self.gridLayout_tasks = QtWidgets.QGridLayout(self.tab_tasks)
        self.gridLayout_tasks.setObjectName("gridLayout_tasks")
        self.tableWidget_tasks = QtWidgets.QTableWidget(parent=self.tab_tasks)
        self.tableWidget_tasks.setAlternatingRowColors(True)
        self.tableWidget_tasks.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget_tasks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget_tasks.setObjectName("tableWidget_tasks")
        self.tableWidget_tasks.setColumnCount(0)
        self.tableWidget_tasks.setRowCount(0)
        self.gridLayout_tasks.addWidget(self.tableWidget_tasks, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_tasks, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 4)
        self.pushButton_refresh = QtWidgets.QPushButton(parent=Dialog_AiTokenUsage)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.gridLayout.addWidget(self.pushButton_refresh, 4, 0, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(parent=Dialog_AiTokenUsage)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout.addWidget(self.pushButton_export, 4, 1, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(parent=Dialog_AiTokenUsage)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 4, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_AiTokenUsage)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 3, 1, 1)

        self.retranslateUi(Dialog_AiTokenUsage)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_AiTokenUsage.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_AiTokenUsage.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_AiTokenUsage)

    def retranslateUi(self, Dialog_AiTokenUsage):
        _translate = QtCore.QCoreApplication.translate
        Dialog_AiTokenUsage.setWindowTitle(_translate("Dialog_AiTokenUsage", "AI Token Usage"))
        self.label_title.setText(_translate("Dialog_AiTokenUsage", "AI token consumption"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_models), _translate("Dialog_AiTokenUsage", "By provider and model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tasks), _translate("Dialog_AiTokenUsage", "By feature"))
        self.pushButton_refresh.setToolTip(_translate("Dialog_AiTokenUsage", "Reload the consumption data"))
        self.pushButton_refresh.setText(_translate("Dialog_AiTokenUsage", "Refresh"))
        self.pushButton_export.setToolTip(_translate("Dialog_AiTokenUsage", "Export the detailed usage list to a CSV file"))
        self.pushButton_export.setText(_translate("Dialog_AiTokenUsage", "Export CSV"))
        self.pushButton_reset.setToolTip(_translate("Dialog_AiTokenUsage", "Delete all recorded usage for this project"))
        self.pushButton_reset.setText(_translate("Dialog_AiTokenUsage", "Reset"))
