# Form implementation generated from reading ui file 'ui_dialog_code_picker.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_code_picker(object):
    def setupUi(self, Dialog_code_picker):
        Dialog_code_picker.setObjectName("Dialog_code_picker")
        Dialog_code_picker.resize(560, 620)
        Dialog_code_picker.setSizeGripEnabled(True)
        self.verticalLayout_main = QtWidgets.QVBoxLayout(Dialog_code_picker)
        self.verticalLayout_main.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_search = QtWidgets.QHBoxLayout()
        self.horizontalLayout_search.setObjectName("horizontalLayout_search")
        self.label_filter_icon = QtWidgets.QLabel(parent=Dialog_code_picker)
        self.label_filter_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.label_filter_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.label_filter_icon.setText("")
        self.label_filter_icon.setObjectName("label_filter_icon")
        self.horizontalLayout_search.addWidget(self.label_filter_icon)
        self.lineEdit_search = QtWidgets.QLineEdit(parent=Dialog_code_picker)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout_search.addWidget(self.lineEdit_search)
        self.pushButton_clear_filter = QtWidgets.QPushButton(parent=Dialog_code_picker)
        self.pushButton_clear_filter.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_clear_filter.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_clear_filter.setText("")
        self.pushButton_clear_filter.setObjectName("pushButton_clear_filter")
        self.horizontalLayout_search.addWidget(self.pushButton_clear_filter)
        self.pushButton_pinned_only = QtWidgets.QPushButton(parent=Dialog_code_picker)
        self.pushButton_pinned_only.setMinimumSize(QtCore.QSize(28, 28))
        self.pushButton_pinned_only.setMaximumSize(QtCore.QSize(28, 28))
        self.pushButton_pinned_only.setText("")
        self.pushButton_pinned_only.setCheckable(True)
        self.pushButton_pinned_only.setObjectName("pushButton_pinned_only")
        self.horizontalLayout_search.addWidget(self.pushButton_pinned_only)
        self.verticalLayout_main.addLayout(self.horizontalLayout_search)
        self.treeWidget = QtWidgets.QTreeWidget(parent=Dialog_code_picker)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_main.addWidget(self.treeWidget)
        self.label_status = QtWidgets.QLabel(parent=Dialog_code_picker)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_main.addWidget(self.label_status)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_code_picker)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_main.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_code_picker)
        QtCore.QMetaObject.connectSlotsByName(Dialog_code_picker)
        Dialog_code_picker.setTabOrder(self.lineEdit_search, self.pushButton_clear_filter)
        Dialog_code_picker.setTabOrder(self.pushButton_clear_filter, self.pushButton_pinned_only)
        Dialog_code_picker.setTabOrder(self.pushButton_pinned_only, self.treeWidget)

    def retranslateUi(self, Dialog_code_picker):
        _translate = QtCore.QCoreApplication.translate
        Dialog_code_picker.setWindowTitle(_translate("Dialog_code_picker", "Find and apply code"))
        self.lineEdit_search.setToolTip(_translate("Dialog_code_picker", "<html><head/><body><p>Code name filter</p></body></html>"))
        self.lineEdit_search.setPlaceholderText(_translate("Dialog_code_picker", "Filter codes"))
        self.pushButton_clear_filter.setToolTip(_translate("Dialog_code_picker", "Clear code filter"))
        self.pushButton_pinned_only.setToolTip(_translate("Dialog_code_picker", "Show pinned codes only"))
        self.treeWidget.setToolTip(_translate("Dialog_code_picker", "<html><head/><body><p>Codes tree. Right click for options</p></body></html>"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog_code_picker", "Name"))
